apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: observability-eks
  region: us-east-1
  version: "1.29"

vpc:
  id: "vpc-093baf06295163b5c"
  subnets:
    private:
      us-east-1a:
        id: "subnet-046c6ade9f09f49ed"
      us-east-1b:
        id: "subnet-031ac2ebd2cb6aece"

managedNodeGroups:
  - name: private-ng
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
    iam:
      withAddonPolicies:
        cloudWatch: true
        autoScaler: true