apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: observability-eks
  region: us-east-1
  version: "1.29"

vpc:
  id: "{vpc_id}"
  subnets:
    private:
      us-east-1a:
        id: "{subnet_id}"
      us-east-1b:
        id: "{subnet_id}}"

managedNodeGroups:
  - name: private-ng
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
    iam:
      withAddonPolicies:
        cloudWatch: true
        autoScaler: true